### PR TITLE
Get CI working again

### PR DESCRIPTION
**Pull request by FlyGoat**
Fix various bits and get CI working again.

Updated source is tested against `test_integration.py` test case and no regression observed so far.

In my run most sources were updated successfully despite cv32e40p which requires manual intervention as https://github.com/litex-hub/pythondata-cpu-cv32e40p/pull/3.

```
Module: cv32e40p
  download: ✓ Success
  update  : ✗ Failed
    Error: Command '['git', 'subtree', 'pull', '-P', 'pythondata_cpu_cv32e40p/system_verilog', '/home/runner/work/pythondata-auto/pythondata-auto/srcs/pythondata-cpu-cv32e40p', '360d272898d81806be[33771](https://github.com/FlyGoat/pythondata-auto/actions/runs/12528018962/job/34942183621#step:5:33829)93870dbf83a3ea79f', '-m', b'Bump pythondata_cpu_cv32e40p/system_verilog subtree to 360d272898d81806be3377193870dbf83a3ea79f\n\nUpdated using 0.0.post148 from https://github.com/litex-hub/litex-data-auto\n']' returned non-zero exit status 1.

Module: cv32e40x
  download: ✓ Success
  update  : ✓ Success

Module: cv32e40s
  download: ✓ Success
  update  : ✓ Success

Module: cv32e41p
  download: ✓ Success
  update  : ✓ Success

Module: cva5
  download: ✓ Success
  update  : ✓ Success

Module: cva6
  download: ✓ Success
  update  : ✓ Success

Module: ibex
  download: ✓ Success
  update  : ✓ Success

Module: lm32
  download: ✓ Success
  update  : ✓ Success

Module: marocchino
  download: ✓ Success
  update  : ✓ Success

Module: microwatt
  download: ✓ Success
  update  : ✓ Success

Module: minerva
  download: ✓ Success
  update  : ✓ Success

Module: mor1kx
  download: ✓ Success
  update  : ✓ Success

Module: opentitan
  download: ✓ Success
  update  : ✓ Success

Module: picorv32
  download: ✓ Success
  update  : ✓ Success

Module: rocket
  download: ✓ Success
  update  : ✓ Success

Module: serv
  download: ✓ Success
  update  : ✓ Success

Module: vexriscv
  download: ✓ Success
  update  : ✓ Success

Module: picolibc
  download: ✓ Success
  update  : ✓ Success

Module: tapcfg
  download: ✓ Success
  update  : ✓ Success

Statistics:
download: 19/19 successful
update  : 18/19 successful
push    : 0/0 successful
```

### CODE REVIEW

**Comment by FlyGoat** [comment]
@enjoy-digital Do you mind merging this and re-enable CI job here: https://github.com/litex-hub/pythondata-auto/actions/workflows/ci.yml ?

I'm trying to get more cores working with CI and it seems like many of them require bumping from upstream.

Thanks

**Comment by enjoy-digital** [comment]
Thanks @FlyGoat, this is merged.

**Comment by FlyGoat** [comment]
@enjoy-digital It seems like GitHub token for this bot is no longer valid, do you mind to refresh it or possibly create a new bot account for it?

Thanks

**Comment by enjoy-digital** [comment]
Thanks @FlyGoat for the feedback. @mithro: do you know more about the bot account / github token, should switch to a different account?

**Pull request merged**
